### ISSUE TITLE
base todo 

### ISSUE THREAD

**Issue by zcorrea357** [darkcode357/thgcmd#3]
- [ ] Type Hints https://www.python.org/dev/peps/pep-0484/ [** ricardo and gabriel yala **] proofing by [** gabriel toroni **]

- [ ] Refactoring performance [** general **]

- [ ] Future implementations [** general **]

  - [ ] create release version [** dark **]

  - [ ] Create setup for the application [shell script install] [** ricardo **]

    - [ ] Create pipenv business rules [** ricardo **]

      - [ ] For the application [** dark **]

        - [ ] stable requirements [** dark **]

      - [ ] For devs [** ricardo + dark **]

        - [ ] requisition for development environment [** ricardo + dark **]

          - [ ] `` `bash
            export GITHUB_USERNAME = YOUR_USERNAME_FOR_GITHUB
            export GITHUB_EMAIL = YOUR_EMAIL_ADDRESS_FOR_GITHUB
            ``

        - [ ] pycharm, vscode, sublime ignore in .gitignore

  - [ ] Create thgcmd description within the wiki [** dark + gabriel toroni **]

    - [ ] Which is ? [** dark + gabriel toroni **]
    - [ ] For what server? [** dark + gabriel toroni **]
    - [ ] How to use ? [** dark + gabriel toroni **]

**Comment by RodrigoMachado9** [comment]
ricardo -> rodrigo
